name: flutter_custom_tabs_web
description: Web platform implementation of flutter_custom_tabs.
version: 1.0.0
homepage: https://github.com/droibit/flutter_custom_tabs

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_custom_tabs_platform_interface:
    git:
      url: https://github.com/snkrdunk/flutter_custom_tabs.git
      ref: develop
      path: flutter_custom_tabs_platform_interface
  meta: ^1.3.0
  url_launcher_web: ^2.0.1
  url_launcher_platform_interface: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0  

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CustomTabsPlugin
        fileName: flutter_custom_tabs_web.dart